id: I6CDDDA40
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:10:37.085770+00:00
last_modified: 2022-12-14 18:10:37.085776+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-18T06:29:42.095Z'
  creationid: dirk
  eft-text-id: UT22084-060-005
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_176-Vimalakirtinirdesa-v1
bases:
  31BF:
    source_metadata: null
    order: 1
    base_file: 31BF.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
